<?php
/**
 * Form: Test form
 * Version: 1
 * Table: form_data.test_form_v1
 * Generated: 2026-07-29 12:43:12
 *
 * Generated by the form builder as a self-contained page.
 *  - the $form array to rename fields, change labels, or tweak types
 *  - the VALIDATION section for additional checks
 *  - the HTML below for layout, styling, or conditional logic
 */

require_once __DIR__ . '/../code/includes/db_connection.php';
require_once __DIR__ . '/../code/includes/functions.php';
require_once __DIR__ . '/../code/includes/auth.php';
require_once __DIR__ . '/../code/models/FormSubmissions.php';

requireAuth(true);

$patientData = getSessionPatientData();
$patientId = $patientData['patient_id'];
$patientNumber = $patientData['patient_number'];

if (!$patientId) {
    setFlash('error', 'Please select a valid patient before completing a form.');
    redirect('/patient-entry.php');
}


// -- Form Definition --
// Edit field labels, types, required status, or add/remove fields here. Changes to field_name or data_type may require a matching database migration.

$form = [
    'form_id' => 36,
    'form_name' => 'Test form',
    'form_description' => 'test form demo',
    'form_version' => 1,
    'table_name' => 'form_data.test_form_v1',
    'fields' => [
        [
            'field_label' => 'D.O.B',
            'field_name' => 'dob',
            'field_type' => 'text',
            'data_type' => 'VARCHAR',
            'is_required' => true,
        ],
        [
            'field_label' => 'Name',
            'field_name' => 'name',
            'field_type' => 'text',
            'data_type' => 'VARCHAR',
            'is_required' => true,
        ],
        [
            'field_label' => 'Surname',
            'field_name' => 'surname',
            'field_type' => 'text',
            'data_type' => 'VARCHAR',
            'is_required' => true,
            'field_options' => '{"_section":"Patient details"}',
        ],
        [
            'field_label' => 'Phone Number',
            'field_name' => 'phone_number',
            'field_type' => 'number',
            'data_type' => 'INTEGER',
            'is_required' => true,
            'field_options' => '{"_section":"Patient details"}',
        ],
    ],
];

$pageTitle = 'Complete: ' . $form['form_name'];
$errors = [];

$submissions = new FormSubmissions();


// POST handler. Two submit buttons share name="_action". A "draft" action saves the current values without validation. A "complete" action runs validation, persists the submission, and redirects to the dashboard on success.
if (isPost()) {
    requireCsrfToken();
    $action = post('_action', 'complete');

    $fieldNames = array_column($form['fields'], 'field_name');
    $data = [];

    foreach ($form['fields'] as $field) {
        $name = $field['field_name'];
        $value = post($name);

        if ($field['field_type'] === 'checkbox' && is_array($value)) {
            $value = json_encode($value);
        }
        if ($field['field_type'] === 'boolean') {
            $value = $value ? '1' : '0';
        }

        $data[$name] = $value;
    }

    if ($action === 'draft') {
        try {
            $draftId = $submissions->saveDraft(
                $form['form_id'],
                $patientId,
                $form['table_name'],
                $fieldNames,
                $data,
                getUserId()
            );

            auditLog('form_draft_save', 'form_submissions', $draftId,
                "Draft saved for \"Test form\" / patient " . $patientNumber);

            setFlash('success', 'Draft saved.');
            redirect($_SERVER['REQUEST_URI']);
        } catch (Exception $e) {
            $errors['_draft'] = 'Draft save failed: ' . $e->getMessage();
        }
    } else {
        // -- VALIDATION --
        // Required-field checks for this form. Errors are keyed by field_name so the form-signature partial can match on key and mark its inputs as invalid via aria attributes.

        foreach ($form['fields'] as $field) {
            if ($field['is_required']) {
                $val = $data[$field['field_name']] ?? '';
                if ($val === '' || $val === null) {
                    $errors[$field['field_name']] = $field['field_label'] . ' is required.';
                }
            }
        }

        // -- Electronic signature --
        // Both the typed name and the attestation checkbox are required for completion. Drafts (handled above) never reach this branch so they skip the check by design.
        $signatureName = trim((string) post('signature_name', ''));
        $signatureConfirmed = !empty($_POST['signature_confirmed']);

        if ($signatureName === '') {
            $errors['signature_name'] = 'Please type your full name to sign this submission.';
        }
        if (!$signatureConfirmed) {
            $errors['signature_confirmed'] = 'Please tick the box to confirm your electronic signature.';
        }

        // -- Custom validation --
        // Add developer-defined rules here. Examples:
        //
        // if (!empty($data['email']) && !filter_var($data['email'], FILTER_VALIDATE_EMAIL)) {
        //     $errors['email'] = 'Please enter a valid email address.';
        // }
        //
        // if (($data['systolic'] ?? 0) > 300) {
        //     $errors['systolic'] = 'Systolic reading seems unusually high - please verify.';
        // }

        // -- Save --
        if (empty($errors)) {
            try {
                $submissionId = $submissions->complete(
                    $form['form_id'],
                    $patientId,
                    $form['table_name'],
                    $fieldNames,
                    $data,
                    getUserId(),
                    $signatureName
                );

                auditLog('form_submit', 'form_submissions', $submissionId,
                    "Submitted \"Test form\" for patient " . $patientNumber);

                setFlash('success', "Submitted as #{$submissionId}.");
                redirect('/index.php');
            } catch (Exception $e) {
                $errors['_submit'] = 'Submission failed: ' . $e->getMessage();
            }
        }
    }
}


// -- Draft rehydration --
// On GET (or on a validation-failed POST), prefill inputs from any existing draft for this (form, patient). POST values always win over draft values.
$existingDraft = $submissions->getDraftForPatient(
    (int) $form['form_id'],
    (int) $patientId,
    $form['table_name']
);
$draftValues = $existingDraft['data'] ?? [];
$draftSavedAt = $existingDraft ? date('d M Y H:i', strtotime($existingDraft['saved_at'])) : null;

$prefill = function (string $name) use ($draftValues) {
    return post($name, $draftValues[$name] ?? '');
};


// -- HTML --
// All form CSS classes are defined in /css/main.css. Add form-specific overrides in a <style> block here if needed.
include __DIR__ . '/../code/views/layouts/header.php';
?>

<div class="form-page">

    <div class="form-back-link-wrap">
        <a href="/form-complete.php" class="form-back-link">
            &larr; Back to form list
        </a>
    </div>

    <!--  Patient Banner  -->
    <div class="patient-banner">
        <div class="patient-banner-left">
            <div class="patient-avatar">
                <?= strtoupper(substr($patientData['patient_name'] ?? 'P', 0, 1)) ?>
            </div>
            <div>
                <p class="patient-banner-name"><?= escape($patientData['patient_name'] ?? 'Unknown Patient') ?></p>
                <p class="patient-banner-sub">Selected patient</p>
            </div>
        </div>
        <div class="patient-banner-right">
            <div class="patient-chip">
                <span class="patient-chip-label">MRN</span>
                <span class="patient-chip-value"><?= escape($patientNumber) ?></span>
            </div>
            <div class="patient-chip">
                <span class="patient-chip-label">Staff</span>
                <span class="patient-chip-value"><?= escape($patientData['username'] ?? '') ?></span>
            </div>
            <div class="patient-chip">
                <span class="patient-chip-label">Date</span>
                <span class="patient-chip-value"><?= date('d M Y') ?></span>
            </div>
            <div class="patient-chip">
                <span class="patient-chip-label">Time</span>
                <span class="patient-chip-value"><?= date('H:i') ?></span>
            </div>
        </div>
    </div>

    <!--  Form Header  -->
    <div class="form-meta-header">
        <div class="form-meta-title">
            <h1>Test form</h1>
            <p>test form demo</p>
        </div>
        <div class="form-meta-details">
            <span><span class="patient-chip-label">Form ID</span> <strong>#36</strong></span>
            <span><span class="patient-chip-label">Fields</span> <strong>4</strong></span>
            <span><span class="patient-chip-label">Version</span> <strong>1</strong></span>
        </div>
    </div>

    <!--  Form Body  -->
    <form method="POST" action="">
        <?= csrfField() ?>
        <div class="form-body">

            <?php if (!empty($errors)): ?>
                <div class="error-list">
                    <strong>Please correct the following before submitting:</strong>
                    <ul>
                        <?php foreach ($errors as $error): ?>
                            <li><?= escape($error) ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>

            <!--  Form Fields  -->
            <!-- Edit the HTML below to change layout, add conditional logic, -->
            <!-- insert custom elements, or override field rendering. -->

<div class="form-group">
    <label for="dob">D.O.B <span class="required">*</span></label>
    <input type="text" id="dob" name="dob" class="form-control" value="<?= escape($prefill('dob')) ?>" required>
</div>
<div class="form-group">
    <label for="name">Name <span class="required">*</span></label>
    <input type="text" id="name" name="name" class="form-control" value="<?= escape($prefill('name')) ?>" required>
</div>
<div class="form-section">
    <div class="form-section-heading">Patient details</div>
    <div class="form-field-grid form-field-grid--sectioned">
<div class="form-group">
    <label for="surname">Surname <span class="required">*</span></label>
    <input type="text" id="surname" name="surname" class="form-control" value="<?= escape($prefill('surname')) ?>" required>
</div>
<div class="form-group">
    <label for="phone_number">Phone Number <span class="required">*</span></label>
    <input type="number" id="phone_number" name="phone_number" class="form-control" value="<?= escape($prefill('phone_number')) ?>" required>
</div>
</div></div>

        </div>

        <!--  Electronic Signature -->
        <!-- Sits in the same position on every generated form: below the last -->
        <!-- field, above the action bar. Edit the partial to change wording. -->
        <?php include __DIR__ . '/../code/views/layouts/form-signature.php'; ?>

        <!--  Form Footer  -->
        <!-- Standard action bar: Cancel / Print / Save Draft / Save & Complete. -->
        <!-- Edit the partial at code/views/layouts/form-actions.php to adjust   -->
        <!-- buttons across every generated form in one place. -->
        <?php include __DIR__ . '/../code/views/layouts/form-actions.php'; ?>
    </form>

</div>

<?php include __DIR__ . '/../code/views/layouts/footer.php'; ?>